name: Generate configuration

on:
  schedule:
    - cron: '18 0 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: python3 run.py
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ (github.event.schedule && 'nightly') || github.event.inputs.tag }}
          files: |
            *.txt
            *.conf
            *.hosts
