name: Generate configuration

on:
  schedule:
    - cron: '18 0 * * 2,4,6'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          CLOUDFLARE_WORKERS_DOMAIN: ${{ secrets.CLOUDFLARE_WORKERS_DOMAIN }}
        run: |
          python3 run.py
          for name in CHN CHN.GOOG CHN.AAPL CHN.ALL   # accelerated-domains apple.china google.china all
          do
            for suffix in .list .txt .conf .hosts
            do
              curl -sSL "https://${CLOUDFLARE_WORKERS_DOMAIN}/chn-domains-list/${name}${suffix}" -o "${name}${suffix}"
            done
          done
          sha256sum CHN.*
          sha256sum accelerated-domains.china.*
          sha256sum apple.china.*
          sha256sum google.china.*
          sha256sum all.*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ (github.event.schedule && 'nightly') || github.event.inputs.tag }}
          files: |
            *.txt
            *.conf
            *.hosts
            *.list
